export const Users = [
  {
    id: 1,
    profilePicture: "person/image4.jpg",
    username: "Safak Kocaoglu",
  },
  {
    id: 2,
    profilePicture: "person/image5.jpg",
    username: "Safak Kocaoglu",
  },
  {
    id: 3,
    profilePicture: "person/image6.jpg",
    username: "Janell Kocaoglu",
  },
  {
    id: 4,
    profilePicture: "person/image5.jpg",
    username: "Kim Kocaoglu",
  },
  {
    id: 5,
    profilePicture: "person/image6.jpg",
    username: "Hide Kocaoglu",
  },
  {
    id: 6,
    profilePicture: "person/image4.jpg",
    username: "Bidid Kocaoglu",
  },
  {
    id: 7,
    profilePicture: "person/image6.jpg",
    username: "Azeez Kocaoglu",
  },
  {
    id: 8,
    profilePicture: "person/image4.jpg",
    username: "Fanboy Kocaoglu",
  },
  {
    id: 9,
    profilePicture: "person/image5.jpg",
    username: "Util Kocaoglu",
  },
  {
    id: 10,
    profilePicture: "person/image4.jpg",
    username: "Safak Kocaoglu",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image6.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image2.jpg",
    date: "5 mins ago",
    userId: 2,
    like: 32,
    comment: 9,
  },
  {
    id: 3,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image1.jpg",
    date: "5 mins ago",
    userId: 3,
    like: 55,
    comment: 9,
  },
  {
    id: 4,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image3.jpg",
    date: "5 mins ago",
    userId: 4,
    like: 32,
    comment: 9,
  },
  {
    id: 5,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image6.jpg",
    date: "5 mins ago",
    userId: 5,
    like: 32,
    comment: 9,
  },
  {
    id: 6,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image3.jpg",
    date: "5 mins ago",
    userId: 6,
    like: 2,
    comment: 90,
  },
  {
    id: 7,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image1.jpg",
    date: "5 mins ago",
    userId: 7,
    like: 2,
    comment: 9,
  },
  {
    id: 8,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image1.jpg",
    date: "5 mins ago",
    userId: 8,
    like: 2,
    comment: 9,
  },
  {
    id: 9,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image1.jpg",
    date: "5 mins ago",
    userId: 9,
    like: 2,
    comment: 9,
  },
  {
    id: 10,
    desc: "Love for All, Hatred fo None.",
    photo: "post/image1.jpg",
    date: "5 mins ago",
    userId: 10,
    like: 2,
    comment: 9,
  },
];
